### ISSUE TITLE
*DIR isn't fully implemented

### ISSUE THREAD

**Issue by marrold** [gfoot/serialfs#5]
I noticed *DIR doesn't work and I can't quite get my head around the intended behaviour.

The do_dir function only allows a directory of a single character. I've created such a directory but it doesn't show with *CAT and while the *DIR command returns successfully, the directory is unchanged.  

This doesn't particularly affect my use case but perhaps *DIR should return the "Unsupported API" error until it's fully implemented to avoid confusion.

**Comment by gfoot** [comment]
*DIR is intended to work how it does in DFS rather than ADFS - so it's nothing to do with directories on the host, it just applies a single-character dot-separated prefix to the filename.  It's not like ADFS, though it would be nice to implement it that way - just not what I needed at the time.  I can't remember but I think I may have experimented with doing it the ADFS way at one point, but (a) have never used ADFS; and (b) couldn't make it then be DFS-compatible, so it might not be possible to support both cases in the same code.

e.g. with an empty disc image, you can type SAVE "MYPROG" and it will write a file called $.MYPROG; and SAVE "X.MYPROG2" will write X.MYPROG2.  Now *DIR X followed by *LOAD "MYPROG2" will work, a *CAT's output should be pretty much the same as what DFS woud say in these cases.  On the host these files are all stored in one directory (or SSD file).

If you want to open other host directories then you need to mount them using *DIN, possibly as separate drives if you also want to be able to still access the previous mount.  e.g. *DIN 1 DEFAULT/SUBDIR works to mount the subdir on drive 1, while keeping the existing mount for drive 0 open as well.  *DCAT won't list such subdirectories as options for mountting (though maybe it should)

**Comment by marrold** [comment]
Ah yes totally understood. I've mostly been using ADFS and a L3 File Server so I totally over looked the way DFS operates. I've since tested what you described and its working as intended.
